//
// Created by PC Mateo on 19/03/2022.
//
#include <fstream>
#include "Matriz.h"

using namespace std;

Matriz::Matriz() {}

Matriz::Matriz(int _filas, int _columnas) {
    filas = _filas;
    columnas = _columnas;
}

int Matriz::getFilas() {
    return filas;
}

int Matriz::getColumnas() {
    return columnas;
}

void Matriz::setColumnas(int _columna) {
    columnas = _columna;
}

void Matriz::setFilas(int _fila) {
    filas = _fila;
}

string Matriz::operacionesMatricesJcoco() {
    string codigoJcoco = "Function: main/0\n"
                         "Constants: None, " + to_string(getFilas()) + ", \"Ingrese el número de la columna:\", 1, \", fila:\", \"para la primera matriz\", \"\", \"para la segunda matriz\"\n"
                         "Locals: n, matriz1, matriz2, j, i, num\n"
                         "Globals: range, append, print, int, input, operacionesMatriz\n"
                         "\n"
                         "BEGIN\n"
                         "          LOAD_CONST                1\n"
                         "          STORE_FAST                0\n"
                         "\n"
                         "          ; Creacion de las 2 matrices\n"
                         "          BUILD_LIST                0\n"
                         "          STORE_FAST                1\n"
                         "          BUILD_LIST                0\n"
                         "          STORE_FAST                2\n"
                         "\n"
                         "          ; Pedir datos al usuario de la primera matriz\n"
                         "          LOAD_GLOBAL               0\n"
                         "          LOAD_FAST                 0\n"
                         "          CALL_FUNCTION             1\n"
                         "          GET_ITER\n"
                         "    etiqueta4: FOR_ITER             etiqueta1\n"
                         "          STORE_FAST                3\n"
                         "          LOAD_FAST                 1\n"
                         "          LOAD_ATTR                 1\n"
                         "          BUILD_LIST                0\n"
                         "          CALL_FUNCTION             1\n"
                         "          POP_TOP\n"
                         "          LOAD_GLOBAL               0\n"
                         "          LOAD_FAST                 0\n"
                         "          CALL_FUNCTION             1\n"
                         "          GET_ITER\n"
                         "    etiqueta3: FOR_ITER             etiqueta2\n"
                         "          STORE_FAST                4\n"
                         "          LOAD_GLOBAL               2\n"
                         "          LOAD_CONST                2\n"
                         "          LOAD_FAST                 4\n"
                         "          LOAD_CONST                3\n"
                         "          BINARY_ADD\n"
                         "          LOAD_CONST                4\n"
                         "          LOAD_FAST                 3\n"
                         "          LOAD_CONST                3\n"
                         "          BINARY_ADD\n"
                         "          LOAD_CONST                5\n"
                         "          CALL_FUNCTION             5\n"
                         "          POP_TOP\n"
                         "          LOAD_GLOBAL               3\n"
                         "          LOAD_GLOBAL               4\n"
                         "          LOAD_CONST                6\n"
                         "          CALL_FUNCTION             1\n"
                         "          CALL_FUNCTION             1\n"
                         "          STORE_FAST                5\n"
                         "          LOAD_FAST                 1\n"
                         "          LOAD_FAST                 3\n"
                         "          BINARY_SUBSCR\n"
                         "          LOAD_ATTR                 1\n"
                         "          LOAD_FAST                 5\n"
                         "          CALL_FUNCTION             1\n"
                         "          POP_TOP\n"
                         "          JUMP_ABSOLUTE             etiqueta3\n"
                         "    etiqueta2: JUMP_ABSOLUTE        etiqueta4\n"
                         "\n"
                         "          ; Pedir datos al usuario de la segunda matriz\n"
                         "    etiqueta1: LOAD_GLOBAL          0\n"
                         "          LOAD_FAST                 0\n"
                         "          CALL_FUNCTION             1\n"
                         "          GET_ITER\n"
                         "    etiqueta8: FOR_ITER             etiqueta5\n"
                         "          STORE_FAST                3\n"
                         "          LOAD_FAST                 2\n"
                         "          LOAD_ATTR                 1\n"
                         "          BUILD_LIST                0\n"
                         "          CALL_FUNCTION             1\n"
                         "          POP_TOP\n"
                         "          LOAD_GLOBAL               0\n"
                         "          LOAD_FAST                 0\n"
                         "          CALL_FUNCTION             1\n"
                         "          GET_ITER\n"
                         "    etiqueta7: FOR_ITER             etiqueta6\n"
                         "          STORE_FAST                4\n"
                         "          LOAD_GLOBAL               2\n"
                         "          LOAD_CONST                2\n"
                         "          LOAD_FAST                 4\n"
                         "          LOAD_CONST                3\n"
                         "          BINARY_ADD\n"
                         "          LOAD_CONST                4\n"
                         "          LOAD_FAST                 3\n"
                         "          LOAD_CONST                3\n"
                         "          BINARY_ADD\n"
                         "          LOAD_CONST                7\n"
                         "          CALL_FUNCTION             5\n"
                         "          POP_TOP\n"
                         "          LOAD_GLOBAL               3\n"
                         "          LOAD_GLOBAL               4\n"
                         "          LOAD_CONST                6\n"
                         "          CALL_FUNCTION             1\n"
                         "          CALL_FUNCTION             1\n"
                         "          STORE_FAST                5\n"
                         "          LOAD_FAST                 2\n"
                         "          LOAD_FAST                 3\n"
                         "          BINARY_SUBSCR\n"
                         "          LOAD_ATTR                 1\n"
                         "          LOAD_FAST                 5\n"
                         "          CALL_FUNCTION             1\n"
                         "          POP_TOP\n"
                         "          JUMP_ABSOLUTE             etiqueta7\n"
                         "    etiqueta6: JUMP_ABSOLUTE        etiqueta8\n"
                         "\n"
                         "          ; Llamar funcion operacionesMatriz\n"
                         "    etiqueta5: LOAD_GLOBAL          5\n"
                         "          LOAD_FAST                 1\n"
                         "          LOAD_FAST                 2\n"
                         "          CALL_FUNCTION             2\n"
                         "          POP_TOP\n"
                         "          LOAD_CONST                0\n"
                         "          RETURN_VALUE\n"
                         "END\n"
                         "\n"
                         "Function: operacionesMatriz/2\n"
                         "Constants: None, 0, \"Suma:\", \"Resta:\", \"Multiplicación:\", \"División:\"\n"
                         "Locals: matriz1, matriz2, suma, resta, multiplicacion, division, j, i\n"
                         "Globals: range, len, append, print\n"
                         "\n"
                         "BEGIN\n"
                         "          ; Se crea una matriz para cada operación\n"
                         "          BUILD_LIST                0\n"
                         "          STORE_FAST                2\n"
                         "          BUILD_LIST                0\n"
                         "          STORE_FAST                3\n"
                         "          BUILD_LIST                0\n"
                         "          STORE_FAST                4\n"
                         "          BUILD_LIST                0\n"
                         "          STORE_FAST                5\n"
                         "\n"
                         "          ; Se inicializa en 0 cada matriz anteriormente creada\n"
                         "          LOAD_GLOBAL               0\n"
                         "          LOAD_GLOBAL               1\n"
                         "          LOAD_FAST                 0\n"
                         "          CALL_FUNCTION             1\n"
                         "          CALL_FUNCTION             1\n"
                         "          GET_ITER\n"
                         "    etiqueta2: FOR_ITER             etiqueta1\n"
                         "          STORE_FAST                6\n"
                         "          LOAD_FAST                 2\n"
                         "          LOAD_ATTR                 2\n"
                         "          BUILD_LIST                0\n"
                         "          CALL_FUNCTION             1\n"
                         "          POP_TOP\n"
                         "          LOAD_FAST                 3\n"
                         "          LOAD_ATTR                 2\n"
                         "          BUILD_LIST                0\n"
                         "          CALL_FUNCTION             1\n"
                         "          POP_TOP\n"
                         "          LOAD_FAST                 4\n"
                         "          LOAD_ATTR                 2\n"
                         "          BUILD_LIST                0\n"
                         "          CALL_FUNCTION             1\n"
                         "          POP_TOP\n"
                         "          LOAD_FAST                 5\n"
                         "          LOAD_ATTR                 2\n"
                         "          BUILD_LIST                0\n"
                         "          CALL_FUNCTION             1\n"
                         "          POP_TOP\n"
                         "          LOAD_GLOBAL               0\n"
                         "          LOAD_GLOBAL               1\n"
                         "          LOAD_FAST                 0\n"
                         "          CALL_FUNCTION             1\n"
                         "          CALL_FUNCTION             1\n"
                         "          GET_ITER\n"
                         "    etiqueta4: FOR_ITER             etiqueta3\n"
                         "          STORE_FAST                7\n"
                         "\n"
                         "          ; Inicialización suma\n"
                         "          LOAD_FAST                 2\n"
                         "          LOAD_FAST                 6\n"
                         "          BINARY_SUBSCR\n"
                         "          LOAD_ATTR                 2\n"
                         "          LOAD_CONST                1\n"
                         "          CALL_FUNCTION             1\n"
                         "          POP_TOP\n"
                         "\n"
                         "          ; Inicialización resta\n"
                         "          LOAD_FAST                 3\n"
                         "          LOAD_FAST                 6\n"
                         "          BINARY_SUBSCR\n"
                         "          LOAD_ATTR                 2\n"
                         "          LOAD_CONST                1\n"
                         "          CALL_FUNCTION             1\n"
                         "          POP_TOP\n"
                         "\n"
                         "          ; Inicialización multiplicación\n"
                         "          LOAD_FAST                 4\n"
                         "          LOAD_FAST                 6\n"
                         "          BINARY_SUBSCR\n"
                         "          LOAD_ATTR                 2\n"
                         "          LOAD_CONST                1\n"
                         "          CALL_FUNCTION             1\n"
                         "          POP_TOP\n"
                         "\n"
                         "          ; Inicialización división\n"
                         "          LOAD_FAST                 5\n"
                         "          LOAD_FAST                 6\n"
                         "          BINARY_SUBSCR\n"
                         "          LOAD_ATTR                 2\n"
                         "          LOAD_CONST                1\n"
                         "          CALL_FUNCTION             1\n"
                         "          POP_TOP\n"
                         "\n"
                         "          JUMP_ABSOLUTE             etiqueta4\n"
                         "    etiqueta3: JUMP_ABSOLUTE        etiqueta2\n"
                         "\n"
                         "          ; Operaciones con las matrices\n"
                         "    etiqueta1: LOAD_GLOBAL          0\n"
                         "          LOAD_GLOBAL               1\n"
                         "          LOAD_FAST                 0\n"
                         "          CALL_FUNCTION             1\n"
                         "          CALL_FUNCTION             1\n"
                         "          GET_ITER\n"
                         "    etiqueta6: FOR_ITER             etiqueta5\n"
                         "          STORE_FAST                6\n"
                         "          LOAD_GLOBAL               0\n"
                         "          LOAD_GLOBAL               1\n"
                         "          LOAD_FAST                 0\n"
                         "          CALL_FUNCTION             1\n"
                         "          CALL_FUNCTION             1\n"
                         "          GET_ITER\n"
                         "    etiqueta8: FOR_ITER             etiqueta7\n"
                         "          STORE_FAST                7\n"
                         "\n"
                         "          ; Suma\n"
                         "          LOAD_FAST                 0\n"
                         "          LOAD_FAST                 6\n"
                         "          BINARY_SUBSCR\n"
                         "          LOAD_FAST                 7\n"
                         "          BINARY_SUBSCR\n"
                         "          LOAD_FAST                 1\n"
                         "          LOAD_FAST                 6\n"
                         "          BINARY_SUBSCR\n"
                         "          LOAD_FAST                 7\n"
                         "          BINARY_SUBSCR\n"
                         "          BINARY_ADD\n"
                         "          LOAD_FAST                 2\n"
                         "          LOAD_FAST                 6\n"
                         "          BINARY_SUBSCR\n"
                         "          LOAD_FAST                 7\n"
                         "          STORE_SUBSCR\n"
                         "\n"
                         "          ; Resta\n"
                         "          LOAD_FAST                 0\n"
                         "          LOAD_FAST                 6\n"
                         "          BINARY_SUBSCR\n"
                         "          LOAD_FAST                 7\n"
                         "          BINARY_SUBSCR\n"
                         "          LOAD_FAST                 1\n"
                         "          LOAD_FAST                 6\n"
                         "          BINARY_SUBSCR\n"
                         "          LOAD_FAST                 7\n"
                         "          BINARY_SUBSCR\n"
                         "          BINARY_SUBTRACT\n"
                         "          LOAD_FAST                 3\n"
                         "          LOAD_FAST                 6\n"
                         "          BINARY_SUBSCR\n"
                         "          LOAD_FAST                 7\n"
                         "          STORE_SUBSCR\n"
                         "          JUMP_ABSOLUTE             etiqueta8\n"
                         "    etiqueta7: JUMP_ABSOLUTE        etiqueta6\n"
                         "\n"
                         "          ; Multiplicación\n"
                         "    etiqueta5: LOAD_GLOBAL          0\n"
                         "          LOAD_GLOBAL               1\n"
                         "          LOAD_FAST                 0\n"
                         "          CALL_FUNCTION             1\n"
                         "          CALL_FUNCTION             1\n"
                         "          GET_ITER\n"
                         "    etiqueta10: FOR_ITER            etiqueta9\n"
                         "          STORE_FAST                5\n"
                         "          LOAD_GLOBAL               0\n"
                         "          LOAD_GLOBAL               1\n"
                         "          LOAD_FAST                 1\n"
                         "          LOAD_CONST                1\n"
                         "          BINARY_SUBSCR\n"
                         "          CALL_FUNCTION             1\n"
                         "          CALL_FUNCTION             1\n"
                         "          GET_ITER\n"
                         "    etiqueta12: FOR_ITER            etiqueta11\n"
                         "          STORE_FAST                6\n"
                         "          LOAD_GLOBAL               0\n"
                         "          LOAD_GLOBAL               1\n"
                         "          LOAD_FAST                 1\n"
                         "          CALL_FUNCTION             1\n"
                         "          CALL_FUNCTION             1\n"
                         "          GET_ITER\n"
                         "    etiqueta14: FOR_ITER             etiqueta13\n"
                         "          STORE_FAST                7\n"
                         "          LOAD_FAST                 4\n"
                         "          LOAD_FAST                 5\n"
                         "          BINARY_SUBSCR\n"
                         "          LOAD_FAST                 6\n"
                         "          BINARY_SUBSCR\n"
                         "          LOAD_FAST                 0\n"
                         "          LOAD_FAST                 5\n"
                         "          BINARY_SUBSCR\n"
                         "          LOAD_FAST                 7\n"
                         "          BINARY_SUBSCR\n"
                         "          LOAD_FAST                 1\n"
                         "          LOAD_FAST                 7\n"
                         "          BINARY_SUBSCR\n"
                         "          LOAD_FAST                 6\n"
                         "          BINARY_SUBSCR\n"
                         "          BINARY_MULTIPLY\n"
                         "          BINARY_ADD\n"
                         "          LOAD_FAST                 4\n"
                         "          LOAD_FAST                 5\n"
                         "          BINARY_SUBSCR\n"
                         "          LOAD_FAST                 6\n"
                         "          STORE_SUBSCR\n"
                         "          JUMP_ABSOLUTE             etiqueta14\n"
                         "    etiqueta13: JUMP_ABSOLUTE       etiqueta12\n"
                         "    etiqueta11: JUMP_ABSOLUTE       etiqueta10\n"
                         "\n"
                         "          ; Imprimir los resultados\n"
                         "          ; Imprimir resultado Suma\n"
                         "    etiqueta9: LOAD_GLOBAL          3\n"
                         "          LOAD_CONST                2\n"
                         "          CALL_FUNCTION             1\n"
                         "          POP_TOP\n"
                         "          LOAD_FAST                 2\n"
                         "          GET_ITER\n"
                         "    etiqueta16: FOR_ITER            etiqueta15\n"
                         "          STORE_FAST                7\n"
                         "          LOAD_GLOBAL               3\n"
                         "          LOAD_FAST                 7\n"
                         "          CALL_FUNCTION             1\n"
                         "          POP_TOP\n"
                         "          JUMP_ABSOLUTE             etiqueta16\n"
                         "    \n"
                         "          ; Imprimir resultado Resta\n"
                         "    etiqueta15: LOAD_GLOBAL          3\n"
                         "          LOAD_CONST                3\n"
                         "          CALL_FUNCTION             1\n"
                         "          POP_TOP\n"
                         "          LOAD_FAST                 3\n"
                         "          GET_ITER\n"
                         "    etiqueta18: FOR_ITER            etiqueta17\n"
                         "          STORE_FAST                7\n"
                         "          LOAD_GLOBAL               3\n"
                         "          LOAD_FAST                 7\n"
                         "          CALL_FUNCTION             1\n"
                         "          POP_TOP\n"
                         "          JUMP_ABSOLUTE             etiqueta18\n"
                         "\n"
                         "          ; Imprimir resultado Multiplicación\n"
                         "    etiqueta17: LOAD_GLOBAL         3\n"
                         "          LOAD_CONST                4\n"
                         "          CALL_FUNCTION             1\n"
                         "          POP_TOP\n"
                         "          LOAD_FAST                 4\n"
                         "          GET_ITER\n"
                         "    etiqueta20: FOR_ITER            etiqueta19\n"
                         "          STORE_FAST                7\n"
                         "          LOAD_GLOBAL               3\n"
                         "          LOAD_FAST                 7\n"
                         "          CALL_FUNCTION             1\n"
                         "          POP_TOP\n"
                         "          JUMP_ABSOLUTE             etiqueta20\n"
                         "\n"
                         "    etiqueta19: LOAD_CONST          0\n"
                         "          RETURN_VALUE\n"
                         "END";

    return codigoJcoco;
}